import getPostComments from '@/lib/getPostComments';
import getSinglePost from '@/lib/getSinglePost';
import React from 'react';

export async function generateMetadata({ params }) {
    let { id } = params;
    let post = await getSinglePost(id)
    return {
        title: post.title,
        description: "Generated by create next app",
    }
}

const SinglePost = async ({ params }) => {
    let { id } = params;
    let postPromise = getSinglePost(id)
    let commentPromise = getPostComments(id)

    let [post, comment] = await Promise.all([postPromise, commentPromise]);

    console.log(comment);

    return (
        <div>
            <h1 className='my-2'>{post.id}</h1>
            <h1 className='my-2'>{post.title}</h1>
            <h1 className='my-2'>{post.body}</h1>
            <hr />

            <div className='grid grid-cols-4 gap-10'>
                {
                    comment?.map(comment => (
                        <div className='bg-stone-700 text-white' key={comment.id}>
                            <h1>{comment.id}</h1>
                            <h1>{comment.name}</h1>
                            <h1>{comment.email}</h1>
                            <h1>{comment.body}</h1>
                        </div>
                    ))
                }
            </div>
        </div>
    );
};

export default SinglePost;